on: push
name: Jira Issue Creation Demo
jobs:
  jiraIssueCreation:
    name: Jira Issue Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Jira Creation Demo
        uses: senzing-factory/github-action-jira-issue-creation@master
        env:
          JIRA_ACCOUNT_URL: https://someaccount.atlassian.net/
          #checkov:skip=CKV_SECRET_6:Not a secret, just an example
          JIRA_API_TOKEN: jiraApiToken
          JIRA_ISSUE_ATTACHMENT: log_file.log
          JIRA_ISSUE_DESCRIPTION: Demo'ing Jira Issue Creation
          JIRA_ISSUE_SUMMARY: Demo'ing Jira Issue Creation
          JIRA_ISSUE_TYPE: Demo'ing Jira Issue Creation
          JIRA_PROJECT: github-action-jira-issue-creation
          JIRA_USERNAME: user@email.com
